version: '3.8'  # Specify the version of the docker-compose file format

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_KEYSPACE: your_keyspace_name  # Optional: Define a keyspace
    networks:
      - app-network

  app:
    build:
      context: .  
    container_name: graphql_app
    depends_on:
      - cassandra
    environment:
      SPRING_APPLICATION_NAME: graphql-workshop
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra  # Ensure this is correct
      SPRING_DATA_CASSANDRA_PORT: 9042
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
